"""messages latency_ms

Revision ID: 173f0ad47b50
Revises: ae6ebcdfb291
Create Date: 2026-06-21 01:04:44.500733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '173f0ad47b50'
down_revision: Union[str, None] = 'ae6ebcdfb291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('latency_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'latency_ms')
    # ### end Alembic commands ###
