"""tenants + tenant_id scoping

Revision ID: 664f7b961f14
Revises: 1d05c26977aa
Create Date: 2026-06-21 00:31:00.050091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664f7b961f14'
down_revision: Union[str, None] = '1d05c26977aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    op.add_column('documents', sa.Column('tenant_id', sa.Uuid(), nullable=False))
    op.drop_index('ix_documents_status_created', table_name='documents')
    op.create_index('ix_documents_tenant_status_created', 'documents', ['tenant_id', 'status', 'created_at'], unique=False)
    op.create_foreign_key(op.f('fk_documents_tenant_id_tenants'), 'documents', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('tenant_id', sa.Uuid(), nullable=False))
    op.create_index('ix_users_tenant_id', 'users', ['tenant_id'], unique=False)
    op.create_foreign_key(op.f('fk_users_tenant_id_tenants'), 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_tenant_id_tenants'), 'users', type_='foreignkey')
    op.drop_index('ix_users_tenant_id', table_name='users')
    op.drop_column('users', 'tenant_id')
    op.drop_constraint(op.f('fk_documents_tenant_id_tenants'), 'documents', type_='foreignkey')
    op.drop_index('ix_documents_tenant_status_created', table_name='documents')
    op.create_index('ix_documents_status_created', 'documents', ['status', 'created_at'], unique=False)
    op.drop_column('documents', 'tenant_id')
    op.drop_table('tenants')
    # ### end Alembic commands ###
