"""message trace fields

Revision ID: 6b88fc68637e
Revises: 173f0ad47b50
Create Date: 2026-06-21 06:05:06.958496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b88fc68637e'
down_revision: Union[str, None] = '173f0ad47b50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('grounding', sa.Float(), nullable=True))
    op.add_column('messages', sa.Column('self_corrected', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('messages', sa.Column('used_web_search', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'used_web_search')
    op.drop_column('messages', 'self_corrected')
    op.drop_column('messages', 'grounding')
    # ### end Alembic commands ###
