"""initial metadata schema

Revision ID: ebc06f85b25a
Revises: 
Create Date: 2026-06-20 10:42:07.046021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebc06f85b25a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_type', sa.Enum('pdf', 'markdown', 'html', 'code', 'notion', 'url', 'text', name='sourcetype', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'ready', 'failed', name='documentstatus', native_enum=False, create_constraint=True, length=16), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index('ix_documents_status_created', 'documents', ['status', 'created_at'], unique=False)
    op.create_index('ix_documents_uri', 'documents', ['uri'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('heading_path', sa.Text(), nullable=True),
    sa.Column('qdrant_point_id', sa.Uuid(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position >= 0', name=op.f('ck_chunks_position_non_negative')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks'))
    )
    op.create_index('uq_chunks_document_position', 'chunks', ['document_id', 'position'], unique=True)
    op.create_index('uq_chunks_qdrant_point_id', 'chunks', ['qdrant_point_id'], unique=True)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('queued', 'running', 'succeeded', 'failed', name='ingestionstate', native_enum=False, create_constraint=True, length=16), server_default='queued', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_ingestion_jobs_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_jobs'))
    )
    op.create_index('ix_ingestion_jobs_document_created', 'ingestion_jobs', ['document_id', 'created_at'], unique=False)
    op.create_index('ix_ingestion_jobs_state_created', 'ingestion_jobs', ['state', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingestion_jobs_state_created', table_name='ingestion_jobs')
    op.drop_index('ix_ingestion_jobs_document_created', table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    op.drop_index('uq_chunks_qdrant_point_id', table_name='chunks')
    op.drop_index('uq_chunks_document_position', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('ix_documents_uri', table_name='documents')
    op.drop_index('ix_documents_status_created', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
